name: Acceptance

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint-and-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Lint codebase
      run: npm run lint

    - name: Cypress tests
      run: npm run test
      env:
        WIKI_TOKEN: ${{ secrets.WIKI_TOKEN }}

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: cypress-screenshots
        path: ./cypress/screenshots

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: cypress-videos
        path: ./cypress/videos
